# Generated by Django 5.0.6 on 2024-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0003_alter_korisnik_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='tip',
            field=models.CharField(choices=[('R', 'Registrovani Korisnik'), ('U', 'Urednik'), ('A', 'Administrator')], db_column='Tip', default='A', max_length=1),
        ),
    ]
