# Generated by Django 5.0.6 on 2024-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0006_diskusija_naslov_diskusije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanak',
            name='broj_ocena',
            field=models.IntegerField(db_column='BrojOcena', default=0),
        ),
        migrations.AlterField(
            model_name='clanak',
            name='zbir_ocena',
            field=models.IntegerField(db_column='ZbirOcena', default=0),
        ),
    ]
