# Generated by Django 5.0.6 on 2024-05-14 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0007_alter_clanak_broj_ocena_alter_clanak_zbir_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pticatabela',
            name='tezina',
            field=models.DecimalField(blank=True, db_column='Tezina', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pticatabela',
            name='velicina',
            field=models.DecimalField(blank=True, db_column='Velicina', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
