# Generated by Django 5.0.6 on 2024-05-22 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0008_alter_pticatabela_tezina_alter_pticatabela_velicina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskusija',
            name='datum_vreme_kreiranja',
            field=models.DateTimeField(db_column='DatumVremeKreiranja', default=django.utils.timezone.localtime),
        ),
    ]
