# Generated by Django 5.0.6 on 2024-05-25 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0010_alter_clanak_datum_vreme_kreiranja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijavljennaobavestenja',
            name='id_prijava_obavestenja',
            field=models.CharField(db_column='IDPrijavaObavestenja', default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prijavljennaobavestenja',
            name='id_korisnika',
            field=models.ForeignKey(db_column='IDKorisnika', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
