# Generated by Django 5.0.6 on 2024-05-25 11:29

from django.db import migrations



def populate_idprijava_obavestenja(apps, schema_editor):
    PrijavljenNaObavestenja = apps.get_model('slobodna_enciklopedija_ptica_srbije', 'PrijavljenNaObavestenja')
    for obj in PrijavljenNaObavestenja.objects.all():
        obj.id_prijava_obavestenja = "1-1"
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0011_prijavljennaobavestenja_id_prijava_obavestenja_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_idprijava_obavestenja)
    ]
