# Generated by Django 5.0.6 on 2024-05-25 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0015_delete_prijavljennaobavestenja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrijavljenNaObavestenja',
            fields=[
                ('id_prijava_obavestenja', models.AutoField(db_column='IDPrijavaObavestenja', primary_key=True, serialize=False)),
                ('datum_vreme_prijave', models.DateTimeField(db_column='DatumVremePrijave', default=django.utils.timezone.now)),
                ('primaj_na_mail', models.IntegerField(db_column='PrimajNaMail')),
                ('id_clanka', models.ForeignKey(db_column='IDClanka', on_delete=django.db.models.deletion.PROTECT, to='slobodna_enciklopedija_ptica_srbije.clanak')),
                ('id_korisnika', models.ForeignKey(db_column='IDKorisnika', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrijavljenNaObavestenja',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='prijavljennaobavestenja',
            constraint=models.UniqueConstraint(fields=('id_korisnika', 'id_clanka'), name='combination_pks'),
        ),
    ]
