# Generated by Django 5.0.6 on 2024-05-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0016_prijavljennaobavestenja_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimljenePoruke',
        ),
    ]
