# Generated by Django 5.0.6 on 2024-05-25 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0017_delete_primljeneporuke'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimljenePoruke',
            fields=[
                ('id_primljena_poruka', models.AutoField(db_column='IDPrijavaObavestenja', primary_key=True, serialize=False)),
                ('procitana', models.IntegerField(db_column='Procitana')),
                ('id_korisnika', models.ForeignKey(db_column='IDKorisnika', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_poruke', models.ForeignKey(db_column='IDPoruke', on_delete=django.db.models.deletion.PROTECT, to='slobodna_enciklopedija_ptica_srbije.poruka')),
            ],
            options={
                'db_table': 'PrimljenePoruke',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='primljeneporuke',
            constraint=models.UniqueConstraint(fields=('id_poruke', 'id_korisnika'), name='combination_pks_primljena_poruka'),
        ),
    ]
