# Generated by Django 5.0.6 on 2024-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0018_primljeneporuke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primljeneporuke',
            name='id_primljena_poruka',
            field=models.AutoField(db_column='IDPrimljenaPoruka', primary_key=True, serialize=False),
        ),
    ]
