# Generated by Django 5.0.6 on 2024-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0019_alter_primljeneporuke_id_primljena_poruka'),
    ]

    operations = [
        migrations.AddField(
            model_name='primljeneporuke',
            name='id_prijavljene_stvari',
            field=models.IntegerField(db_column='IDPrijavljeneStvari', default=0),
        ),
        migrations.AddField(
            model_name='primljeneporuke',
            name='tip_prijave',
            field=models.CharField(choices=[('D', 'Diskusija'), ('K', 'Komentar'), ('F', 'Fotografija'), ('C', 'Clanak')], db_column='TipPrijave', default='C', max_length=1),
        ),
    ]
