# Generated by Django 5.0.6 on 2024-05-30 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0020_primljeneporuke_id_prijavljene_stvari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijavljennaobavestenja',
            name='datum_vreme_prijave',
            field=models.DateTimeField(db_column='DatumVremePrijave', default=django.utils.timezone.localtime),
        ),
        migrations.DeleteModel(
            name='Ocena',
        ),
    ]
