# Generated by Django 5.0.6 on 2024-05-30 09:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0021_alter_prijavljennaobavestenja_datum_vreme_prijave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id_ocene', models.AutoField(db_column='IDOcene', primary_key=True, serialize=False)),
                ('datum_vreme_ocenjivanja', models.DateTimeField(db_column='DatumVremeOcenjivanja', default=django.utils.timezone.localtime)),
                ('ocena', models.IntegerField(db_column='Ocena', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('id_clanka', models.ForeignKey(db_column='IDClanka', on_delete=django.db.models.deletion.PROTECT, to='slobodna_enciklopedija_ptica_srbije.clanak')),
                ('id_korisnika', models.ForeignKey(db_column='IDKorisnika', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ocena',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='ocena',
            constraint=models.UniqueConstraint(fields=('id_korisnika', 'id_clanka'), name='idKor_idCla_unique'),
        ),
    ]
