# Generated by Django 5.0.6 on 2024-05-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobodna_enciklopedija_ptica_srbije', '0022_ocena_ocena_idkor_idcla_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='id_diskusije',
            field=models.ForeignKey(db_column='IDDiskusije', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.diskusija'),
        ),
        migrations.AlterField(
            model_name='nepravilnostclanak',
            name='id_clanka',
            field=models.ForeignKey(db_column='IDClanka', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.clanak'),
        ),
        migrations.AlterField(
            model_name='nepravilnostclanak',
            name='id_prijave',
            field=models.OneToOneField(db_column='IDPrijave', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slobodna_enciklopedija_ptica_srbije.prijavanepravilnosti'),
        ),
        migrations.AlterField(
            model_name='nepravilnostdiskusija',
            name='id_diskusije',
            field=models.ForeignKey(db_column='IDDiskusije', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.diskusija'),
        ),
        migrations.AlterField(
            model_name='nepravilnostdiskusija',
            name='id_prijave',
            field=models.OneToOneField(db_column='IDPrijave', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slobodna_enciklopedija_ptica_srbije.prijavanepravilnosti'),
        ),
        migrations.AlterField(
            model_name='nepravilnostfotografija',
            name='id_fotografije',
            field=models.ForeignKey(db_column='IDFotografije', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.fotografijagalerija'),
        ),
        migrations.AlterField(
            model_name='nepravilnostfotografija',
            name='id_prijave',
            field=models.OneToOneField(db_column='IDPrijave', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slobodna_enciklopedija_ptica_srbije.prijavanepravilnosti'),
        ),
        migrations.AlterField(
            model_name='nepravilnostkomentar',
            name='id_komentara',
            field=models.ForeignKey(db_column='IDKomentara', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.komentar'),
        ),
        migrations.AlterField(
            model_name='nepravilnostkomentar',
            name='id_prijave',
            field=models.OneToOneField(db_column='IDPrijave', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='slobodna_enciklopedija_ptica_srbije.prijavanepravilnosti'),
        ),
        migrations.AlterField(
            model_name='prijavljennaobavestenja',
            name='id_clanka',
            field=models.ForeignKey(db_column='IDClanka', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.clanak'),
        ),
        migrations.AlterField(
            model_name='primljeneporuke',
            name='id_poruke',
            field=models.ForeignKey(db_column='IDPoruke', on_delete=django.db.models.deletion.CASCADE, to='slobodna_enciklopedija_ptica_srbije.poruka'),
        ),
    ]
